services:
  portfolio_site_cms:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
      args:
        VITE_APP_NODE_ENV: ${VITE_APP_NODE_ENV}
        VITE_APP_BACKEND_URL: ${VITE_APP_BACKEND_URL}
        VITE_APP_PORT: ${VITE_APP_PORT}
    ports:
      - "${VITE_APP_PORT:-3001}:80"
