/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutTab: typeof import('./components/site-config/AboutTab.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    ColorPickerInput: typeof import('./components/ColorPickerInput.vue')['default']
    ConfirmDialog: typeof import('./components/ConfirmDialog.vue')['default']
    ExperienceFormDialog: typeof import('./components/experience/ExperienceFormDialog.vue')['default']
    FooterTab: typeof import('./components/site-config/FooterTab.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    HomeTab: typeof import('./components/site-config/HomeTab.vue')['default']
    RichTextEditor: typeof import('./components/RichTextEditor.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SystemTab: typeof import('./components/site-config/SystemTab.vue')['default']
    UserFormDialog: typeof import('./components/user/UserFormDialog.vue')['default']
  }
}
