/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutTab: typeof import('./components/site-config/AboutTab.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    ColorPickerInput: typeof import('./components/ColorPickerInput.vue')['default']
    ConfirmDialog: typeof import('./components/ConfirmDialog.vue')['default']
    ExperienceActionsMenu: typeof import('./components/experience/ExperienceActionsMenu.vue')['default']
    ExperienceDescriptionLocaleEditor: typeof import('./components/experience/ExperienceDescriptionLocaleEditor.vue')['default']
    ExperienceDesktopTableCard: typeof import('./components/experience/ExperienceDesktopTableCard.vue')['default']
    ExperienceFormDialog: typeof import('./components/experience/ExperienceFormDialog.vue')['default']
    ExperienceMobileListCard: typeof import('./components/experience/ExperienceMobileListCard.vue')['default']
    ExperienceSkillDialog: typeof import('./components/experience/ExperienceSkillDialog.vue')['default']
    ExperienceSkillsEditor: typeof import('./components/experience/ExperienceSkillsEditor.vue')['default']
    FooterTab: typeof import('./components/site-config/FooterTab.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    HomeTab: typeof import('./components/site-config/HomeTab.vue')['default']
    RichTextEditor: typeof import('./components/RichTextEditor.vue')['default']
    RichTextEditorToolbar: typeof import('./components/rich-text-editor/RichTextEditorToolbar.vue')['default']
    RichTextToolbarAlignButtons: typeof import('./components/rich-text-editor/RichTextToolbarAlignButtons.vue')['default']
    RichTextToolbarBlockMenu: typeof import('./components/rich-text-editor/RichTextToolbarBlockMenu.vue')['default']
    RichTextToolbarHistoryButtons: typeof import('./components/rich-text-editor/RichTextToolbarHistoryButtons.vue')['default']
    RichTextToolbarLinkButtons: typeof import('./components/rich-text-editor/RichTextToolbarLinkButtons.vue')['default']
    RichTextToolbarListButtons: typeof import('./components/rich-text-editor/RichTextToolbarListButtons.vue')['default']
    RichTextToolbarMarkButtons: typeof import('./components/rich-text-editor/RichTextToolbarMarkButtons.vue')['default']
    RichTextToolbarMiscButtons: typeof import('./components/rich-text-editor/RichTextToolbarMiscButtons.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SystemTab: typeof import('./components/site-config/SystemTab.vue')['default']
    UserActionsMenu: typeof import('./components/user/UserActionsMenu.vue')['default']
    UserFormDialog: typeof import('./components/user/UserFormDialog.vue')['default']
  }
}
